" ---- Plug configuration ----
" auto-install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    echo "Installing VimPlug..."
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall
endif

call plug#begin()

"  - Side nav bar
Plug 'scrooloose/nerdtree'
"  - Status bar
Plug 'bling/vim-airline'
"  - Git commands
Plug 'tpope/vim-fugitive'
"  - Theme onedark
Plug 'joshdick/onedark.vim'
"  - Language pack
Plug 'sheerun/vim-polyglot'
"  - Align code on demand
Plug 'godlygeek/tabular'

call plug#end()
" ------------------------------

"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

if has('gui_running')
  set guifont=FiraCode-Retina:h11
endif

syntax on
colorscheme onedark

map <C-n> :NERDTreeToggle<CR>
function! StartUp()
  if argc() > 0
    execute 'NERDTree' expand(argv(0))
  else
    execute 'NERDTree' expand('%:p:h')
  endif
endfunction
" Open NERDTree in the input file directory 
autocmd VimEnter * call StartUp()
autocmd VimEnter * wincmd p 

set number

let NERDTreeShowHidden=1
let g:terraform_fmt_on_save=1
let g:terraform_align=1

